// flow-typed signature: 96f33d7dd76727d59f35546d9e4e5515
// flow-typed version: <<STUB>>/react-native-global-font_v^1.0.2/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-global-font'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-global-font' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-global-font/example/App' {
  declare module.exports: any;
}

declare module 'react-native-global-font/example' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-global-font/example/App.js' {
  declare module.exports: $Exports<'react-native-global-font/example/App'>;
}
declare module 'react-native-global-font/example/index' {
  declare module.exports: $Exports<'react-native-global-font/example'>;
}
declare module 'react-native-global-font/example/index.js' {
  declare module.exports: $Exports<'react-native-global-font/example'>;
}
declare module 'react-native-global-font/index' {
  declare module.exports: $Exports<'react-native-global-font'>;
}
declare module 'react-native-global-font/index.js' {
  declare module.exports: $Exports<'react-native-global-font'>;
}
