# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    increment_build_number
    match( type: "appstore",
          git_url:"git@github.com:tuzmusic/QMGElectroCerts.git") # more information: https://codesigning.guide   
    gym(scheme: "QMGElectroNative") # Build your app - more options available
    pilot
  end

  lane :inc_version do
    increment_version_number
    increment_build_number(
      build_number: "0" # set a specific number
    )
  end

  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end
